name: pull request

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"
      - name: Install dependencies
        run: sudo apt update && sudo apt install libsqlite3-dev libmagickcore-dev libmagickwand-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          only-new-issues: true
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"
      - name: Install dependencies
        run: sudo apt update && sudo apt install libsqlite3-dev libmagickcore-dev libmagickwand-dev
      - name: Build
        run: make build
